export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const PAGE_RELOAD = "PAGE_RELOAD";

export const ADD_VOUCHER = "ADD_VOUCHER";
export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const DEL_VOUCHER = "DEL_VOUCHER";
export const GET_VOUCHER = "GET_VOUCHER";