export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const PAGE_RELOAD = "PAGE_RELOAD";

export const ADD_VOUCHER = "ADD_VOUCHER";
export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const DEL_VOUCHER = "DEL_VOUCHER";
export const GET_VOUCHER = "GET_VOUCHER";
export const GET_ALL_VOUCHER = "GET_ALL_VOUCHER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const UPDATE_ADMIN_ENTRY = "UPDATE_ADMIN_ENTRY";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_MOBILE = "UPDATE_MOBILE";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ACTIVE = "UPDATE_ACTIVE";